name: EasyTier GUI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  build-gui:
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: x86_64-pc-windows-msvc
            OS: windows-latest
            GUI_TARGET: x86_64-pc-windows-msvc
            ARTIFACT_NAME: windows-x86_64
          - TARGET: i686-pc-windows-msvc
            OS: windows-latest
            GUI_TARGET: i686-pc-windows-msvc
            ARTIFACT_NAME: windows-i686

    runs-on: ${{ matrix.OS }}
    env:
      NAME: easytier
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}
      GUI_TARGET: ${{ matrix.GUI_TARGET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set current ref as env variable
        run: |
          echo "GIT_DESC=$(git log -1 --format=%cd.%h --date=format:%Y-%m-%d_%H:%M:%S)" >> $GITHUB_ENV

      - name: Prepare build environment
        uses: ./.github/actions/prepare-build
        with:
          target: ${{ matrix.TARGET }}
          gui: true
          pnpm: true
          pnpm-build-filter: ''
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "gui-registry"
          cache-targets: "false"

      - name: copy correct DLLs
        run: |
          case $TARGET in
              x86_64*)  ARCH_DIR=x86_64 ;;
              i686*)    ARCH_DIR=i686 ;;
          esac
          if [[ -n "$ARCH_DIR" ]]; then
              find "./easytier/third_party/${ARCH_DIR}" -maxdepth 1 -type f \( -name "*.dll" -o -name "*.sys" \) -exec cp {} ./easytier-gui/src-tauri/ \;
          fi

      - name: Build GUI
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: ./easytier-gui
          args: --verbose --target ${{ matrix.GUI_TARGET }}

      - name: Collect artifact
        run: |
          mkdir -p ./artifacts/
          mv ./target/$GUI_TARGET/release/bundle/nsis/*.exe ./artifacts/ || true

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: easytier-gui-${{ matrix.ARTIFACT_NAME }}
          path: ./artifacts/*
